### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by rtezera1**
- Added unit tests for the various CRUD operations

### CODE REVIEW

**Comment by gedion** [comment]
This is great @rtezera1! You've added 100% code coverage on the handlers functions!
Code review and sanity check passes! 

A very minor feedback would be to do syntax formatting as some of the formatting made it hard to read.

Otherwise this is ready for merging.

Screen Shot 2020-03-29 at 8 59 57 AM
Screen Shot 2020-03-29 at 9 01 09 AM

**Comment by rtezera1** [comment]
Hi @gedion, thanks for the review.  I see what you mean about formatting. I will make those changes. I tried adding `eslint` | `jshint` but later I figured it's better to create a separate branch for that.

**Comment by abelhbeyene** [comment]
@gedion @rtezera1 - FYI added eslint #21

**Comment by abelhbeyene** [comment]
@rtezera1 - please resolve conflicts and let's get this merged. Will be really useful!

**Pull request merged**
